<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from org.project60.sepaterminatemandates/xml/schema/CRM/Sepaterminatemandates/SEPAMandateTerminationCriterion.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:a5345058774f2b7a8a2d8c1b68f2ad03)
 */
use CRM_Sepaterminatemandates_ExtensionUtil as E;

/**
 * Database access object for the SEPAMandateTerminationCriterion entity.
 */
class CRM_Sepaterminatemandates_DAO_SEPAMandateTerminationCriterion extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_sdd_mandate_termination_criterion';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique SEPAMandateTerminationCriterion ID
   *
   * @var int
   */
  public $id;

  /**
   * @var text
   */
  public $description;

  /**
   * @var bool
   */
  public $is_active;

  /**
   * @var text
   */
  public $search_criteria;

  /**
   * @var text
   */
  public $terminate_configuration;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_sdd_mandate_termination_criterion';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('SEPAMandate Termination Criterions') : E::ts('SEPAMandate Termination Criterion');
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('Unique SEPAMandateTerminationCriterion ID'),
          'required' => TRUE,
          'where' => 'civicrm_sdd_mandate_termination_criterion.id',
          'table_name' => 'civicrm_sdd_mandate_termination_criterion',
          'entity' => 'SEPAMandateTerminationCriterion',
          'bao' => 'CRM_Sepaterminatemandates_DAO_SEPAMandateTerminationCriterion',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'description' => [
          'name' => 'description',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Description'),
          'required' => FALSE,
          'where' => 'civicrm_sdd_mandate_termination_criterion.description',
          'table_name' => 'civicrm_sdd_mandate_termination_criterion',
          'entity' => 'SEPAMandateTerminationCriterion',
          'bao' => 'CRM_Sepaterminatemandates_DAO_SEPAMandateTerminationCriterion',
          'localizable' => 0,
          'add' => NULL,
        ],
        'is_active' => [
          'name' => 'is_active',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('Is active'),
          'required' => TRUE,
          'where' => 'civicrm_sdd_mandate_termination_criterion.is_active',
          'default' => '1',
          'table_name' => 'civicrm_sdd_mandate_termination_criterion',
          'entity' => 'SEPAMandateTerminationCriterion',
          'bao' => 'CRM_Sepaterminatemandates_DAO_SEPAMandateTerminationCriterion',
          'localizable' => 0,
          'add' => NULL,
        ],
        'search_criteria' => [
          'name' => 'search_criteria',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Search Criteria'),
          'required' => FALSE,
          'where' => 'civicrm_sdd_mandate_termination_criterion.search_criteria',
          'table_name' => 'civicrm_sdd_mandate_termination_criterion',
          'entity' => 'SEPAMandateTerminationCriterion',
          'bao' => 'CRM_Sepaterminatemandates_DAO_SEPAMandateTerminationCriterion',
          'localizable' => 0,
          'serialize' => self::SERIALIZE_JSON,
          'add' => NULL,
        ],
        'terminate_configuration' => [
          'name' => 'terminate_configuration',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Terminate Configuration'),
          'required' => FALSE,
          'where' => 'civicrm_sdd_mandate_termination_criterion.terminate_configuration',
          'table_name' => 'civicrm_sdd_mandate_termination_criterion',
          'entity' => 'SEPAMandateTerminationCriterion',
          'bao' => 'CRM_Sepaterminatemandates_DAO_SEPAMandateTerminationCriterion',
          'localizable' => 0,
          'serialize' => self::SERIALIZE_JSON,
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'sdd_mandate_termination_criterion', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'sdd_mandate_termination_criterion', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
