-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
-- 

-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from drop.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_sdd_mandate_termination_criterion`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_sdd_mandate_termination_criterion
-- *
-- * Search Criteria for automatically termination of SEPA mandates
-- *
-- *******************************************************/
CREATE TABLE `civicrm_sdd_mandate_termination_criterion` (


     `id` int unsigned NOT NULL AUTO_INCREMENT  COMMENT 'Unique SEPAMandateTerminationCriterion ID',
     `description` text NULL   ,
     `is_active` tinyint NOT NULL  DEFAULT 1 ,
     `search_criteria` text NULL   ,
     `terminate_configuration` text NULL   ,
     `next_check_date` date NULL    
,
        PRIMARY KEY (`id`)
 
 
 
)  ENGINE=InnoDB  ;

 